# Generated by Django 5.0.3 on 2024-03-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
    ]
