# Generated by Django 5.0.3 on 2024-03-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_remove_client_branch_remove_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='addedBy',
            new_name='client_name',
        ),
    ]
